# Generated by Django 3.0.8 on 2020-09-18 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('light_saber_color', models.CharField(max_length=10)),
                ('has_force', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spaceship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spaceship_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_side', models.CharField(choices=[('N', "Doesn't have the force"), ('B', 'Bright side'), ('D', 'Dark side')], default='N', max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='spaceships',
            field=models.ManyToManyField(to='main_app.Spaceship'),
        ),
    ]
